# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: a4337e319d2237a12aaf50fdbf8ec84b2dc06177859447f960d8eed35312256f
    docker:
      # specify the version you desire here
      - image: circleci/node:11
    working_directory: ~/library

    steps:
      - checkout
      - run:
          name: Setup Code Climate test-reporter
          # | indicates there will be more than one shell command to run
          command: |
            mkdir -p temp/
            # fetch the test-reporter pre-built binary and save the binary in cc-test-reporter file
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./temp/cc-test-reporter
            chmod +x ./temp/cc-test-reporter

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install packages
          command: yarn install

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Execute tests and send report to code climate
          command: |
            # run before-build command to notify code climate of a pending test report
            ./temp/cc-test-reporter before-build
            yarn test:coverage
            # run after-build command to notify code climate of a completed test
            ./temp/cc-test-reporter after-build --debug -t lcov coverage/lcov.info --exit-code $?
